### ISSUE TITLE
copyedit

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/help-home-guide#1]
Hi @LornaLynch and @lauraclay,
Could I get a copy edit please?
Thanks

**Comment by LornaLynch** [comment]
CONTRIBUTING and README text relate to a different resource. Do you have a revised text?

**Comment by LornaLynch** [comment]
Formatting on commands.md looks weird from here: this will need to be checked on staging.

**Comment by bennuttall** [comment]
I was going to flag this up. Title and readme and things are left over from copy of QSG.

**Comment by LornaLynch** [comment]
Thanks @bennuttall: sorry to double-up!

**Comment by LornaLynch** [comment]
Links to hard- and software guides in setup.md need fixing when documents are live.

**Comment by LornaLynch** [comment]
Done, but with the points above still needing to be addressed when possible.
